Repository Dataport/polar, pull requests merged in 2023-12, with the labels that each got.

#30 Feature/wfs list
  README.md
  packages/clients/afm/src/polar-client.ts
  packages/clients/dish/src/addPlugins.ts
  packages/clients/meldemichel/CHANGELOG.md
  packages/clients/meldemichel/src/addPlugins.ts
  packages/clients/meldemichel/src/language.ts
  packages/clients/meldemichel/src/mapConfigurations.ts
  packages/clients/meldemichel/src/plugins/Gfi/Feature.vue
  packages/clients/meldemichel/src/plugins/Gfi/index.ts
  packages/clients/meldemichel/src/utils/createMenus.ts
  packages/core/CHANGELOG.md
  packages/core/README.md
  packages/core/src/components/MapContainer.vue
  packages/core/src/vuePlugins/actions/useExtendedMasterportalapiMarkers.ts
  packages/core/src/vuePlugins/vuex.ts
  packages/lib/createTestMountParameters/index.ts
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/README.md
  packages/plugins/Gfi/architecture/initialDraft.drawio
  packages/plugins/Gfi/src/components/Feature.vue
  packages/plugins/Gfi/src/components/FeatureButtonGroup.vue
  packages/plugins/Gfi/src/components/FeatureSwitchButtons.vue
  packages/plugins/Gfi/src/components/FeatureTableBody.vue
  packages/plugins/Gfi/src/components/FeatureTableHead.vue
  packages/plugins/Gfi/src/components/Gfi.vue
  packages/plugins/Gfi/src/components/List.vue
  packages/plugins/Gfi/src/language.ts
  packages/plugins/Gfi/src/store/actions.ts
  packages/plugins/Gfi/src/store/getInitialState.ts
  packages/plugins/Gfi/src/store/getters.ts
  packages/plugins/Gfi/src/types.ts
  packages/plugins/Gfi/src/utils/requestGfi.ts
  packages/plugins/Gfi/src/utils/requestGfiGeoJson.ts
  packages/plugins/IconMenu/CHANGELOG.md
  packages/plugins/IconMenu/src/language.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
  tsconfig.json
Labels: enhancement

#40 refactor address search keyboard navigation
  packages/plugins/AddressSearch/src/components/Results.vue
Labels: refactor

#39 fix listening documentation
  packages/core/CHANGELOG.md
  packages/core/README.md
  packages/plugins/AddressSearch/CHANGELOG.md
  packages/plugins/AddressSearch/README.md
  packages/plugins/Draw/CHANGELOG.md
  packages/plugins/Draw/README.md
  packages/plugins/Export/CHANGELOG.md
  packages/plugins/Export/README.md
  packages/plugins/Fullscreen/CHANGELOG.md
  packages/plugins/Fullscreen/README.md
  packages/plugins/GeoLocation/CHANGELOG.md
  packages/plugins/GeoLocation/README.md
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/README.md
  packages/plugins/LoadingIndicator/CHANGELOG.md
  packages/plugins/LoadingIndicator/README.md
  packages/plugins/Pins/CHANGELOG.md
  packages/plugins/Pins/README.md
  packages/plugins/Zoom/CHANGELOG.md
  packages/plugins/Zoom/README.md
Labels: bug, documentation

#31 Extend accessibility of IconMenu, Features rendered in it and the AfmButton
  packages/clients/meldemichel/src/plugins/AfmButton/AfmButton.vue
  packages/core/CHANGELOG.md
  packages/core/src/components/MapContainer.vue
  packages/core/src/vuePlugins/vuex.ts
  packages/lib/createTestMountParameters/CHANGELOG.md
  packages/lib/createTestMountParameters/index.ts
  packages/plugins/Attributions/CHANGELOG.md
  packages/plugins/Attributions/src/components/AttributionContent.vue
  packages/plugins/Attributions/src/language.ts
  packages/plugins/Export/CHANGELOG.md
  packages/plugins/Export/src/components/Button.vue
  packages/plugins/Fullscreen/CHANGELOG.md
  packages/plugins/Fullscreen/src/components/Fullscreen.vue
  packages/plugins/GeoLocation/CHANGELOG.md
  packages/plugins/GeoLocation/src/components/GeoLocation.vue
  packages/plugins/IconMenu/CHANGELOG.md
  packages/plugins/IconMenu/src/components/IconMenu.vue
  packages/plugins/IconMenu/src/language.ts
  packages/plugins/LayerChooser/CHANGELOG.md
  packages/plugins/LayerChooser/src/components/LayerWrapper.vue
  packages/plugins/Zoom/CHANGELOG.md
  packages/plugins/Zoom/src/components/Zoom.vue
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#38 Feature/gfi tooltip
  packages/clients/meldemichel/src/mapConfigurations.ts
  packages/lib/tooltip/CHANGELOG.md
  packages/lib/tooltip/LICENSE
  packages/lib/tooltip/README.md
  packages/lib/tooltip/index.ts
  packages/lib/tooltip/package.json
  packages/lib/tooltip/tsconfig.json
  packages/lib/tooltip/vite.config.js
  packages/plugins/GeoLocation/package.json
  packages/plugins/GeoLocation/src/store/actions.ts
  packages/plugins/GeoLocation/src/utils/tooltip.ts
  packages/plugins/Gfi/README.md
  packages/plugins/Gfi/package.json
  packages/plugins/Gfi/src/store/actions.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#45 Attributions are now being translated when the window is open
  package-lock.json
  packages/plugins/Attributions/CHANGELOG.md
  packages/plugins/Attributions/package.json
  packages/plugins/Attributions/src/components/AttributionContent.vue
Labels: bug

#42 implement clustering and cluster styles
  packages/clients/meldemichel/package.json
  packages/clients/meldemichel/src/index.html
  packages/clients/meldemichel/src/language.ts
  packages/clients/meldemichel/src/mapConfigurations.ts
  packages/clients/meldemichel/src/polar-client.ts
  packages/clients/meldemichel/src/utils/enableClustering.ts
  packages/clients/meldemichel/src/utils/showTooltip.ts
  packages/core/CHANGELOG.md
  packages/core/README.md
  packages/core/package.json
  packages/core/src/components/MapContainer.vue
  packages/core/src/utils/addClusterStyle.ts
  packages/core/src/utils/markers.ts
  packages/core/src/utils/resolveClusterClick.ts
  packages/core/src/vuePlugins/actions/useExtendedMasterportalapiMarkers.ts
  packages/lib/createTestMountParameters/index.ts
  packages/plugins/Filter/src/utils/updateFeatureVisibility.ts
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/src/store/actions.ts
  packages/plugins/Gfi/src/store/getters.ts
  packages/plugins/Gfi/src/utils/listableLayersFilter.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#47 chore: update documentation
  packages/clients/meldemichel/API.md
  packages/clients/meldemichel/CHANGELOG.md
  packages/clients/meldemichel/example/index.html
  packages/clients/meldemichel/src/html/index.html
Labels: documentation

#48 Update MoveHandle to only be rendered once
  package-lock.json
  package.json
  packages/clients/dish/src/plugins/Gfi/ActionButton.vue
  packages/clients/dish/src/plugins/Gfi/Content.vue
  packages/clients/meldemichel/src/plugins/Gfi/Feature.vue
  packages/clients/meldemichel/src/utils/createMenus.ts
  packages/components/CHANGELOG.md
  packages/components/MoveHandle.vue
  packages/components/package.json
  packages/core/CHANGELOG.md
  packages/core/README.md
  packages/core/package.json
  packages/core/src/components/MapContainer.vue
  packages/core/src/vuePlugins/vuex.ts
  packages/lib/createTestMountParameters/index.ts
  packages/plugins/Attributions/CHANGELOG.md
  packages/plugins/Attributions/README.md
  packages/plugins/Attributions/src/components/AttributionContent.vue
  packages/plugins/Attributions/src/components/Attributions.vue
  packages/plugins/Draw/src/components/Draw.vue
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/README.md
  packages/plugins/Gfi/package.json
  packages/plugins/Gfi/src/components/Feature.vue
  packages/plugins/Gfi/src/components/Gfi.vue
  packages/plugins/Gfi/src/components/List.vue
  packages/plugins/Gfi/src/store/actions.ts
  packages/plugins/Gfi/src/store/getInitialState.ts
  packages/plugins/Gfi/src/store/getters.ts
  packages/plugins/Gfi/src/types.ts
  packages/plugins/IconMenu/CHANGELOG.md
  packages/plugins/IconMenu/README.md
  packages/plugins/IconMenu/src/components/IconMenu.vue
  packages/plugins/IconMenu/src/language.ts
  packages/plugins/IconMenu/src/store/index.ts
  packages/plugins/LayerChooser/src/components/LayerChooser.vue
  packages/plugins/LayerChooser/src/components/Options.vue
  packages/plugins/LayerChooser/src/components/Selection.vue
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement, refactor

#49 melmi colour scheme proposal
  packages/clients/meldemichel/src/mapConfigurations.ts
Labels: accessibility

#43 Feature/wfs list and markers interwoven
  packages/clients/meldemichel/src/language.ts
  packages/clients/meldemichel/src/mapConfigurations.ts
  packages/clients/meldemichel/src/plugins/Gfi/ActionButtons.vue
  packages/clients/meldemichel/src/plugins/Gfi/Feature.vue
  packages/clients/meldemichel/src/utils/createMenus.ts
  packages/clients/meldemichel/src/utils/showTooltip.ts
  packages/components/MoveHandle.vue
  packages/core/README.md
  packages/core/src/vuePlugins/actions/useExtendedMasterportalapiMarkers.ts
  packages/core/src/vuePlugins/actions/useExtendedMasterportalapiMarkers/center.ts
  packages/core/src/vuePlugins/actions/useExtendedMasterportalapiMarkers/getFeaturesCluster.ts
  packages/core/src/vuePlugins/actions/useExtendedMasterportalapiMarkers/index.ts
  packages/core/src/vuePlugins/actions/useExtendedMasterportalapiMarkers/setLayerId.ts
  packages/core/src/vuePlugins/vuex.ts
  packages/plugins/Gfi/README.md
  packages/plugins/Gfi/src/components/List.vue
  packages/plugins/Gfi/src/store/actions.ts
  packages/plugins/Gfi/src/store/getters.ts
  packages/plugins/Gfi/src/types.ts
  packages/plugins/IconMenu/CHANGELOG.md
  packages/plugins/IconMenu/src/store/index.ts
  packages/types/custom/core.ts
Labels: enhancement

#51 add source maps to builds
  viteConfigs/vite.client.js
Labels: enhancement

#56 Update icons of layerChooser to be clearer for the content behind it
  packages/clients/afm/CHANGELOG.md
  packages/clients/afm/src/polar-client.ts
  packages/clients/dish/CHANGELOG.md
  packages/clients/dish/src/addPlugins.ts
  packages/clients/meldemichel/CHANGELOG.md
  packages/clients/meldemichel/src/utils/createMenus.ts
  packages/clients/snowbox/src/addPlugins.ts
Labels: enhancement

#58 Add the possibility to update the icon of the close-button of the MoveHandle
  packages/clients/meldemichel/CHANGELOG.md
  packages/clients/meldemichel/src/plugins/Gfi/Feature.vue
  packages/components/CHANGELOG.md
  packages/components/MoveHandle.vue
  packages/core/CHANGELOG.md
  packages/core/src/components/MapContainer.vue
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/src/components/Gfi.vue
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#61 fix: remove css bleed
  package.json
  packages/clients/afm/API.md
  packages/clients/afm/CHANGELOG.md
  packages/clients/afm/example/polar-example.js
  packages/clients/afm/example/prod-example.html
  packages/clients/dish/README.md
  packages/clients/dish/src/index.html
  packages/clients/meldemichel/API.md
  packages/clients/meldemichel/CHANGELOG.md
  packages/clients/meldemichel/example/complete.html
  packages/clients/meldemichel/example/report.html
  packages/clients/meldemichel/example/single.immovable.html
  packages/clients/meldemichel/example/single.movable.html
  packages/clients/meldemichel/src/html/index.html
  packages/clients/meldemichel/src/index.html
  packages/clients/snowbox/package.json
  packages/clients/snowbox/vite.config.js
  packages/core/CHANGELOG.md
  packages/core/README.md
  packages/core/src/utils/createMap.ts
  packages/core/src/utils/createMap/index.ts
  packages/core/src/utils/createMap/makeShadowRoot.ts
  packages/core/src/utils/createMap/pullPolarStyleToShadow.ts
  packages/core/src/utils/createMap/pullVuetifyStyleToShadow.ts
  packages/core/src/utils/createMap/setupFontawesome.ts
  packages/core/src/utils/createMap/subscribe.ts
  packages/core/src/utils/createMap/updateSizeOnReady.ts
  packages/core/src/vuePlugins/vuetify.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: bug, refactor

#60 document not-anymore-arcane knowledge
  arcana.md
Labels: documentation
