Repository Dataport/polar, pull requests merged in 2023-11, with the labels that each got.

#11 refactor pins module code for readability
  packages/plugins/Pins/src/store/index.ts
Labels: refactor

#2 Feature: Add configuration to add an initial pin which can be centered on
  packages/clients/meldemichel/example/single.immovable.html
  packages/clients/meldemichel/example/single.movable.html
  packages/clients/meldemichel/src/index.html
  packages/clients/meldemichel/src/mapConfigurations.ts
  packages/plugins/Pins/CHANGELOG.md
  packages/plugins/Pins/README.md
  packages/plugins/Pins/src/store/index.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#7 Add staticAttributions linking to the copyright information
  packages/clients/meldemichel/src/mapConfigurations.ts
Labels: enhancement

#10 deduplicate bound layer types
  packages/lib/passesBoundaryCheck/index.ts
  packages/lib/passesBoundaryCheck/package.json
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: refactor

#9 fix icon menu content placement
  packages/plugins/IconMenu/CHANGELOG.md
  packages/plugins/IconMenu/src/components/IconMenu.vue
Labels: bug, refactor

#8 Prepare Meldemichel Alpha
  package.json
  packages/clients/meldemichel/API.md
  packages/clients/meldemichel/example/index.html
  packages/clients/meldemichel/example/report.html
  packages/clients/meldemichel/example/single.immovable.html
  packages/clients/meldemichel/example/single.movable.html
  packages/clients/meldemichel/package.json
  packages/clients/meldemichel/src/hhborder.geojson
  packages/clients/meldemichel/src/index.html
  packages/clients/meldemichel/src/mapConfigurations.ts
  packages/clients/meldemichel/src/store/module.ts
  packages/core/CHANGELOG.md
  packages/core/src/vuePlugins/vuex.ts
  packages/lib/createTestMountParameters/CHANGELOG.md
  packages/lib/createTestMountParameters/index.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
  pages/index.html
  scripts/buildPages.sh
Labels: documentation, enhancement

#14 add config to define behaviour on boundary errors
  packages/clients/meldemichel/src/language.ts
  packages/clients/meldemichel/src/mapConfigurations.ts
  packages/lib/passesBoundaryCheck/CHANGELOG.md
  packages/lib/passesBoundaryCheck/index.ts
  packages/plugins/GeoLocation/CHANGELOG.md
  packages/plugins/GeoLocation/README.md
  packages/plugins/GeoLocation/src/language.ts
  packages/plugins/GeoLocation/src/store/actions.ts
  packages/plugins/GeoLocation/src/store/getters.ts
  packages/plugins/GeoLocation/src/types.ts
  packages/plugins/Pins/CHANGELOG.md
  packages/plugins/Pins/README.md
  packages/plugins/Pins/src/language.ts
  packages/plugins/Pins/src/store/index.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#17 Fix: Icon Menu content overflow
  packages/plugins/IconMenu/src/components/IconMenu.vue
  packages/plugins/IconMenu/src/types.ts
Labels: bug

#16 Fix/#15 wrong mouse cursor
  packages/plugins/Pins/CHANGELOG.md
  packages/plugins/Pins/src/store/index.ts
Labels: bug

#20 Fix: Type access to core configuration
  packages/plugins/AddressSearch/src/store/getters.ts
  packages/plugins/Attributions/src/store/index.ts
  packages/plugins/Draw/src/store/index.ts
  packages/plugins/Fullscreen/src/store/index.ts
  packages/plugins/GeoLocation/src/store/getters.ts
  packages/plugins/Gfi/src/store/getters.ts
  packages/plugins/IconMenu/src/store/index.ts
  packages/plugins/Pins/src/store/index.ts
  packages/plugins/Zoom/src/store/index.ts
Labels: refactor

#18 change @ts-ignore to @ts-expect-error where appropriate
  packages/clients/dish/src/polar-client.ts
  packages/clients/meldemichel/src/mapConfigurations.ts
  packages/clients/meldemichel/src/utils/setBackgroundImage.ts
  packages/core/src/utils/createMap.ts
  packages/core/src/vuePlugins/vuex.ts
  packages/lib/getFeatures/gazetteer/parse.ts
  packages/lib/getFeatures/wfs/parse.ts
  packages/plugins/Gfi/src/store/actions.ts
  packages/plugins/IconMenu/src/store/index.ts
  packages/plugins/ReverseGeocoder/src/utils/reverseGeocode.ts
Labels: documentation

#21 Fix/snowbox improvements
  package.json
  packages/clients/snowbox/package.json
  packages/clients/snowbox/src/addPlugins.ts
  packages/clients/snowbox/src/index.html
  packages/clients/snowbox/src/language.ts
  packages/clients/snowbox/src/mapConfiguration.ts
  packages/plugins/GeoLocation/CHANGELOG.md
  packages/plugins/GeoLocation/README.md
  packages/plugins/GeoLocation/src/components/GeoLocation.vue
  packages/plugins/GeoLocation/src/store/getters.ts
  packages/plugins/GeoLocation/src/types.ts
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/src/components/GfiContent.vue
  packages/plugins/IconMenu/CHANGELOG.md
  packages/plugins/IconMenu/src/components/IconMenu.vue
  packages/plugins/Legend/CHANGELOG.md
  packages/plugins/Legend/src/components/Legend.vue
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
  pages/index.html
Labels: documentation, enhancement

#22 enhance README
  README.md
Labels: documentation

#23 Feature/meldemichel afm button
  packages/clients/meldemichel/API.md
  packages/clients/meldemichel/CHANGELOG.md
  packages/clients/meldemichel/src/html/index.html
  packages/clients/meldemichel/src/index.html
  packages/clients/meldemichel/src/language.ts
  packages/clients/meldemichel/src/mapConfigurations.ts
  packages/clients/meldemichel/src/plugins/AfmButton/AfmButton.vue
  packages/clients/meldemichel/src/plugins/AfmButton/index.ts
  packages/clients/meldemichel/src/plugins/AfmButton/language.ts
  packages/clients/meldemichel/src/polar-client.ts
  packages/clients/meldemichel/src/store/module.ts
Labels: enhancement

#13 Feature: Extend addressSearch accessibility
  packages/clients/meldemichel/src/mapConfigurations.ts
  packages/plugins/AddressSearch/CHANGELOG.md
  packages/plugins/AddressSearch/README.md
  packages/plugins/AddressSearch/src/components/Input.vue
  packages/plugins/AddressSearch/src/components/Results.vue
  packages/plugins/AddressSearch/src/store/getters.ts
  packages/plugins/AddressSearch/src/types.ts
  packages/plugins/AddressSearch/src/utils/focusFirstResult.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#28 Add link to repository and license as required by EUPL v1.2
  packages/plugins/Attributions/CHANGELOG.md
  packages/plugins/Attributions/src/language.ts
  packages/plugins/Attributions/src/utils/lib.ts
  packages/plugins/Attributions/tests/attributions.spec.ts
Labels: enhancement

#32 Fix map overlay being visible on desktop if map is not in focus
  packages/core/src/components/MapContainer.vue
Labels: bug

#29 Chore/package json links
  packages/clients/afm/package.json
  packages/clients/dish/package.json
  packages/clients/meldemichel/package.json
  packages/components/package.json
  packages/core/package.json
  packages/lib/createTestMountParameters/package.json
  packages/lib/getFeatures/package.json
  packages/lib/idx/package.json
  packages/lib/passesBoundaryCheck/package.json
  packages/plugins/AddressSearch/package.json
  packages/plugins/Attributions/package.json
  packages/plugins/Draw/package.json
  packages/plugins/Export/package.json
  packages/plugins/Fullscreen/package.json
  packages/plugins/GeoLocation/package.json
  packages/plugins/Gfi/package.json
  packages/plugins/IconMenu/package.json
  packages/plugins/LayerChooser/package.json
  packages/plugins/Legend/package.json
  packages/plugins/LoadingIndicator/package.json
  packages/plugins/Pins/package.json
  packages/plugins/ReverseGeocoder/package.json
  packages/plugins/Scale/package.json
  packages/plugins/Toast/package.json
  packages/plugins/Zoom/package.json
  packages/types/custom/package.json
Labels: documentation

#36 No timeout for error toasts
  packages/plugins/GeoLocation/src/store/actions.ts
  packages/plugins/Pins/src/store/index.ts
  packages/plugins/Toast/src/store/index.ts
Labels: enhancement
