Repository Dataport/polar, pull requests merged in 2024-09, with the labels that each got.

#171 Documentation - Sorted Readme Parameters by Required and Alphabet
  packages/core/README.md
  packages/plugins/AddressSearch/README.md
  packages/plugins/Gfi/README.md
  packages/plugins/Toast/README.md
  packages/plugins/Zoom/README.md
Labels: documentation

#164 export enum from package root for easier access
  packages/clients/dish/CHANGELOG.md
  packages/clients/dish/src/utils/autocomplete.ts
  packages/clients/textLocator/src/utils/coastalGazetteer/searchToponym.ts
  packages/plugins/AddressSearch/CHANGELOG.md
  packages/plugins/AddressSearch/src/index.ts
  packages/plugins/AddressSearch/src/store/actions.ts
Labels: bug

#167 revised readme for icon menu plugin
  packages/plugins/IconMenu/README.md
Labels: documentation

#170 Documentation - @polar/plugin-address-search & @polar/plugin-gfi
  packages/plugins/AddressSearch/CHANGELOG.md
  packages/plugins/AddressSearch/README.md
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/README.md
Labels: documentation

#169 Documentation - Improved description for addLoading and removeLoading
  packages/plugins/AddressSearch/CHANGELOG.md
  packages/plugins/AddressSearch/README.md
  packages/plugins/ReverseGeocoder/CHANGELOG.md
  packages/plugins/ReverseGeocoder/README.md
Labels: documentation

#150 Fix typing across the project
  .github/workflows/run-tests.yml
  package.json
  packages/core/src/monkeyCrossOrigin.ts
  packages/core/src/monkeyHeaderLoader.ts
  packages/core/src/utils/createMap/setupFontawesome.ts
  packages/plugins/AddressSearch/CHANGELOG.md
  packages/plugins/AddressSearch/src/store/actions.ts
  packages/plugins/AddressSearch/src/types.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
  tsconfig.ci.json
Labels: enhancement

#163 fix type to accomodate for vuex and used field
  packages/clients/dish/CHANGELOG.md
  packages/clients/dish/src/utils/autocomplete.ts
  packages/clients/meldemichel/CHANGELOG.md
  packages/clients/meldemichel/src/mapConfigurations.ts
  packages/clients/textLocator/src/utils/coastalGazetteer/searchToponym.ts
  packages/plugins/AddressSearch/CHANGELOG.md
  packages/plugins/AddressSearch/src/index.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: bug

#162 Feature/choose stroke color for drawing
  packages/plugins/Draw/CHANGELOG.md
  packages/plugins/Draw/README.md
  packages/plugins/Draw/src/components/Draw.vue
  packages/plugins/Draw/src/components/DrawOptions.vue
  packages/plugins/Draw/src/language.ts
  packages/plugins/Draw/src/store/actions.ts
  packages/plugins/Draw/src/store/createInteractions/createModifyInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/index.ts
  packages/plugins/Draw/src/store/createInteractions/modifyDrawStyle.ts
  packages/plugins/Draw/src/store/createInteractions/modifyTextStyle.ts
  packages/plugins/Draw/src/store/index.ts
  packages/plugins/Draw/src/types.ts
  packages/plugins/Draw/src/utils/createDrawStyle.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#174 fix ts client check
  package.json
  packages/clients/dish/src/utils/search.ts
  packages/clients/generic/src/polar-client.ts
  packages/clients/meldemichel/src/addPlugins.ts
  packages/clients/meldemichel/src/utils/createMenus.ts
  packages/types/custom/core.ts
  tsconfig.ci.json
Labels: bug

#153 Chore/upgrade lerna
  .eslintignore
  .prettierignore
  lerna.json
  nx.json
  package-lock.json
  package.json
  packages/clients/afm/package.json
  packages/clients/dish/package.json
  packages/clients/generic/package.json
  packages/clients/meldemichel/package.json
  packages/clients/snowbox/package.json
  packages/clients/textLocator/package.json
  scripts/makeDocs.js
Labels: enhancement

#175 Fix pages:build on MacOS
  scripts/buildPages.sh
Labels: enhancement

#159 Add loader styles
  packages/plugins/LoadingIndicator/CHANGELOG.md
  packages/plugins/LoadingIndicator/README.md
  packages/plugins/LoadingIndicator/assets/BasicLoader.gif
  packages/plugins/LoadingIndicator/assets/CircleLoader.gif
  packages/plugins/LoadingIndicator/assets/RingLoader.gif
  packages/plugins/LoadingIndicator/assets/RollerLoader.gif
  packages/plugins/LoadingIndicator/assets/SpinnerLoader.gif
  packages/plugins/LoadingIndicator/assets/VuetifyLoader.gif
  packages/plugins/LoadingIndicator/readme_loadingIndicator_example.png
  packages/plugins/LoadingIndicator/src/components/LoadingIndicator.vue
  packages/plugins/LoadingIndicator/src/components/loaderStyles/Basic.vue
  packages/plugins/LoadingIndicator/src/components/loaderStyles/Circle.vue
  packages/plugins/LoadingIndicator/src/components/loaderStyles/Ring.vue
  packages/plugins/LoadingIndicator/src/components/loaderStyles/Roller.vue
  packages/plugins/LoadingIndicator/src/components/loaderStyles/Spinner.vue
  packages/plugins/LoadingIndicator/src/store/getters.ts
  packages/plugins/LoadingIndicator/src/store/index.ts
  packages/plugins/LoadingIndicator/src/store/mutations.ts
  packages/plugins/LoadingIndicator/src/store/state.ts
  packages/plugins/LoadingIndicator/src/types.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
  scripts/makeDocs.js
Labels: enhancement

#185 add security.md draft
  security.md
Labels: documentation

#183 #33 refactor unused code by deleting it
  packages/lib/getFeatures/CHANGELOG.md
  packages/lib/getFeatures/gazetteer/index.ts
  packages/lib/getFeatures/gazetteer/parse.ts
  packages/lib/getFeatures/index.ts
  packages/plugins/AddressSearch/README.md
  packages/types/custom/core.ts
Labels: refactor

#178 allow selection escape with escape button
  packages/plugins/AddressSearch/CHANGELOG.md
  packages/plugins/AddressSearch/src/components/Results.vue
  packages/plugins/AddressSearch/src/store/actions.ts
Labels: enhancement

#181 #33 refactor code to match lint rule
  packages/lib/testMountParameters/index.ts
Labels: refactor

#179 #33 refactor code to match lint rules
  packages/plugins/LayerChooser/src/store/index.ts
  packages/plugins/LayerChooser/src/utils/getOpenedOptionsServiceLayers.ts
Labels: refactor

#182 #33 refactor AddressSearch to meet linting requirements
  packages/plugins/AddressSearch/src/store/actions.ts
  packages/plugins/AddressSearch/src/utils/searchMethods/bkg.ts
  packages/plugins/AddressSearch/src/utils/searchMethods/mpapi.ts
Labels: refactor

#176 #33 Refactor/shorten methods above lint treshold
  packages/plugins/Gfi/src/store/actions/debouncedGfiRequest.ts
  packages/plugins/Gfi/src/store/actions/index.ts
  packages/plugins/Gfi/src/utils/getOriginalFeature.ts
  packages/plugins/Gfi/src/utils/requestGfiWfs.ts
  packages/plugins/Gfi/src/utils/requestGfiWms.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: refactor

#184 #33 make failure to adhere to max length catastrophic
  .eslintrc.json
Labels: refactor

#160 Feature/mpapi configuration parameters
  package-lock.json
  packages/clients/dish/src/mapConfig.ts
  packages/clients/meldemichel/src/mapConfigurations.ts
  packages/clients/snowbox/src/mapConfiguration.ts
  packages/clients/textLocator/src/mapConfig.ts
  packages/core/CHANGELOG.md
  packages/core/README.md
  packages/core/src/index.ts
  packages/core/src/utils/createMap/defaults.ts
  packages/core/src/utils/createMap/index.ts
  packages/core/src/vuePlugins/vuex.ts
  packages/lib/testMountParameters/index.ts
  packages/lib/testMountParameters/package.json
  packages/plugins/LayerChooser/CHANGELOG.md
  packages/plugins/LayerChooser/README.md
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
  pages/examples/address.html
  pages/examples/draw.html
  pages/examples/gfi.html
  pages/examples/layer.html
  pages/examples/locales.html
  pages/examples/orientation.html
  pages/examples/render.js
  scripts/makeDocs.js
Labels: documentation

#188 Additionally expose createMap for @polar/client-generic
  packages/clients/generic/CHANGELOG.md
  packages/clients/generic/src/polar-client.ts
  pages/examples/render.js
Labels: enhancement

#166 Feature/geolocation outside extent or boundary
  packages/plugins/GeoLocation/CHANGELOG.md
  packages/plugins/GeoLocation/README.md
  packages/plugins/GeoLocation/src/store/actions.ts
  packages/plugins/GeoLocation/src/store/getInitialState.ts
  packages/plugins/GeoLocation/src/store/getters.ts
  packages/plugins/GeoLocation/src/types.ts
  packages/plugins/GeoLocation/src/utils/positionChanged.ts
Labels: enhancement

#189 Adjust overlay mechanic for macOS devices
  packages/core/CHANGELOG.md
  packages/core/src/components/MapContainer.vue
  packages/core/src/language/locales/de.ts
  packages/core/src/language/locales/en.ts
Labels: bug

#187 Feature/e2e tests poc
  .github/workflows/run-tests.yml
  .gitignore
  e2e/draw.spec.ts
  e2e/pins.spec.ts
  e2e/toast.spec.ts
  e2e/utils/clickTimes.ts
  e2e/utils/openSnowbox.ts
  e2e/utils/vuex.ts
  e2e/zoom.spec.ts
  jest.config.ts
  package-lock.json
  package.json
  packages/clients/snowbox/README.md
  packages/clients/snowbox/src/html/index.html
  packages/clients/snowbox/src/index.html
  packages/clients/snowbox/src/polar-client.ts
  playwright.config.ts
Labels: enhancement
