Repository Dataport/polar, pull requests merged in 2024-07, with the labels that each got.

#115 Add TextLocator client
  package-lock.json
  package.json
  packages/clients/textLocator/API.md
  packages/clients/textLocator/CHANGELOG.md
  packages/clients/textLocator/LICENSE
  packages/clients/textLocator/README.md
  packages/clients/textLocator/package.json
  packages/clients/textLocator/scripts/injectFlag.sh
  packages/clients/textLocator/src/addPlugins.ts
  packages/clients/textLocator/src/components/ResultInfo.vue
  packages/clients/textLocator/src/index.html
  packages/clients/textLocator/src/locales.ts
  packages/clients/textLocator/src/mapConfig.ts
  packages/clients/textLocator/src/palettes.ts
  packages/clients/textLocator/src/plugins/GeometrySearch/components/Action.vue
  packages/clients/textLocator/src/plugins/GeometrySearch/components/DrawMode.vue
  packages/clients/textLocator/src/plugins/GeometrySearch/components/GeometrySearch.vue
  packages/clients/textLocator/src/plugins/GeometrySearch/components/Tree.vue
  packages/clients/textLocator/src/plugins/GeometrySearch/components/ViewToggle.vue
  packages/clients/textLocator/src/plugins/GeometrySearch/components/index.ts
  packages/clients/textLocator/src/plugins/GeometrySearch/index.ts
  packages/clients/textLocator/src/plugins/GeometrySearch/language.ts
  packages/clients/textLocator/src/plugins/GeometrySearch/store/actions/setupDrawReaction.ts
  packages/clients/textLocator/src/plugins/GeometrySearch/store/actions/setupTooltip.ts
  packages/clients/textLocator/src/plugins/GeometrySearch/store/actions/watchers.ts
  packages/clients/textLocator/src/plugins/GeometrySearch/store/index.ts
  packages/clients/textLocator/src/plugins/GeometrySearch/types.ts
  packages/clients/textLocator/src/plugins/GeometrySearch/utils/makeTreeView.ts
  packages/clients/textLocator/src/plugins/GeometrySearch/utils/vectorDisplay.ts
  packages/clients/textLocator/src/plugins/GeometrySearch/utils/vectorStyles.ts
  packages/clients/textLocator/src/plugins/Header/Header.vue
  packages/clients/textLocator/src/plugins/Header/index.ts
  packages/clients/textLocator/src/plugins/Header/language.ts
  packages/clients/textLocator/src/polar-client.ts
  packages/clients/textLocator/src/services.ts
  packages/clients/textLocator/src/utils/coastalGazetteer/common.ts
  packages/clients/textLocator/src/utils/coastalGazetteer/getAllPages.ts
  packages/clients/textLocator/src/utils/coastalGazetteer/getPrimaryName.ts
  packages/clients/textLocator/src/utils/coastalGazetteer/makeRequestBody.ts
  packages/clients/textLocator/src/utils/coastalGazetteer/responseInterpreter.ts
  packages/clients/textLocator/src/utils/coastalGazetteer/searchGeometry.ts
  packages/clients/textLocator/src/utils/coastalGazetteer/searchToponym.ts
  packages/clients/textLocator/src/utils/coastalGazetteer/types.ts
  packages/clients/textLocator/src/utils/common.ts
  packages/clients/textLocator/src/utils/literatureByToponym.ts
  packages/clients/textLocator/tsconfig.json
  packages/clients/textLocator/vite.config.js
  packages/plugins/AddressSearch/CHANGELOG.md
  packages/plugins/AddressSearch/README.md
  packages/plugins/AddressSearch/src/components/Results.vue
  packages/plugins/AddressSearch/src/store/getters.ts
  packages/plugins/AddressSearch/src/types.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
  scripts/buildPages.sh
Labels: enhancement

#139 Fix incorrect link on documentation page linking to plugin gallery
  pages/documentation.html
Labels: bug

#143 remove unused dependencies
  package-lock.json
  package.json
  sbom.json
Labels: refactor

#148 POLAR-362 Update deprecated boolean of movable parameter to enum value
  packages/clients/afm/CHANGELOG.md
  packages/clients/afm/example/polar-example.js
  packages/clients/dish/CHANGELOG.md
  packages/clients/dish/src/mapConfig.ts
  packages/clients/meldemichel/CHANGELOG.md
  packages/clients/meldemichel/src/mapConfigurations.ts
  packages/clients/snowbox/src/mapConfiguration.ts
  packages/plugins/Pins/README.md
  pages/examples/address.html
Labels: documentation, refactor
