Repository Dataport/polar, pull requests merged in 2024-08, with the labels that each got.

#136 Feature/add new mode for attributions
  packages/plugins/Attributions/CHANGELOG.md
  packages/plugins/Attributions/src/components/AttributionContent.vue
  packages/plugins/Attributions/src/types.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#154 Feature/easing between zoom levels
  packages/plugins/Zoom/CHANGELOG.md
  packages/plugins/Zoom/src/store/index.ts
Labels: enhancement

#156 custom attributes for the like filter
  packages/lib/getFeatures/CHANGELOG.md
  packages/lib/getFeatures/types.ts
  packages/lib/getFeatures/wfs/buildWfsFilter.ts
  packages/plugins/AddressSearch/CHANGELOG.md
  packages/plugins/AddressSearch/README.md
Labels: enhancement

#144 Feature/add scale switcher
  packages/plugins/Scale/CHANGELOG.md
  packages/plugins/Scale/README.md
  packages/plugins/Scale/src/components/Scale.vue
  packages/plugins/Scale/src/index.ts
  packages/plugins/Scale/src/store/index.ts
  packages/plugins/Scale/src/types.ts
  packages/plugins/Scale/src/utils/beautifyScale.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#161 markdown heading IDs
  package-lock.json
  package.json
  packages/core/README.md
  scripts/makeDocs.js
Labels: documentation, enhancement

#158 Add example configuration to documentation
  packages/core/README.md
  packages/plugins/AddressSearch/README.md
  packages/plugins/Attributions/README.md
  packages/plugins/Draw/README.md
  packages/plugins/Export/README.md
  packages/plugins/Filter/README.md
  packages/plugins/Fullscreen/README.md
  packages/plugins/GeoLocation/README.md
  packages/plugins/Gfi/README.md
  packages/plugins/LayerChooser/README.md
  packages/plugins/LoadingIndicator/README.md
  packages/plugins/Pins/README.md
  packages/plugins/ReverseGeocoder/README.md
  packages/plugins/Scale/README.md
  packages/plugins/Toast/README.md
  packages/plugins/Zoom/README.md
  scripts/makeDocs.js
Labels: documentation

#155 Fix sass deprecation issue regarding declaration position
  packages/plugins/Gfi/src/components/List.vue
Labels: enhancement

#157 Fix/test warnings
  packages/lib/testMountParameters/CHANGELOG.md
  packages/lib/testMountParameters/index.ts
  packages/plugins/Gfi/tests/actions.spec.ts
Labels: bug
