Repository Dataport/polar, pull requests merged in 2024-11, with the labels that each got.

#191 Getting started guide
  README.md
  gettingStarted.md
Labels: documentation

#197 implement unselectable features
  packages/clients/snowbox/src/language.ts
  packages/clients/snowbox/src/mapConfiguration.ts
  packages/clients/snowbox/src/polar-client.ts
  packages/core/CHANGELOG.md
  packages/core/README.md
  packages/core/src/utils/markers/index.ts
  packages/core/src/vuePlugins/actions/useExtendedMasterportalapiMarkers/index.ts
  packages/core/src/vuePlugins/vuex.ts
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/README.md
  packages/plugins/Gfi/src/store/actions/debouncedGfiRequest.ts
  packages/plugins/Gfi/src/store/getters.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#199 add icon menu test
  e2e/iconMenu.spec.ts
Labels: enhancement

#195 Fix/text locator heatmap
  packages/clients/textLocator/CHANGELOG.md
  packages/clients/textLocator/src/palettes.ts
  packages/clients/textLocator/src/plugins/GeometrySearch/utils/vectorDisplay.ts
  packages/clients/textLocator/src/utils/coastalGazetteer/makeRequestBody.ts
Labels: bug

#194 Feature/text locator result source indicator
  packages/clients/textLocator/CHANGELOG.md
  packages/clients/textLocator/src/plugins/GeometrySearch/components/GeometrySearch.vue
  packages/clients/textLocator/src/plugins/GeometrySearch/language.ts
  packages/clients/textLocator/src/plugins/GeometrySearch/store/index.ts
  packages/clients/textLocator/src/plugins/GeometrySearch/types.ts
  packages/clients/textLocator/src/utils/coastalGazetteer/searchToponym.ts
  packages/clients/textLocator/src/utils/textLocatorBackend/findLiterature/selectLiterature.ts
Labels: enhancement

#201 Feature/gfi multiple features
  packages/clients/snowbox/src/mapConfiguration.ts
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/README.md
  packages/plugins/Gfi/src/store/actions/debouncedGfiRequest.ts
  packages/plugins/Gfi/src/store/actions/index.ts
  packages/plugins/Gfi/src/store/getters.ts
  packages/plugins/Gfi/src/types.ts
  packages/plugins/Gfi/src/utils/requestGfi.ts
  packages/plugins/Gfi/src/utils/requestGfiGeoJson.ts
  packages/plugins/Gfi/src/utils/requestGfiWfs.ts
  packages/plugins/Gfi/tests/actions.spec.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#203 Fix/geojson
  packages/core/README.md
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/src/components/FeatureTableBody.vue
  packages/plugins/Gfi/src/utils/requestGfiGeoJson.ts
Labels: bug
