Repository Dataport/polar, pull requests merged in 2024-06, with the labels that each got.

#127 Fix initiallyOpen not working in prod mode
  packages/core/CHANGELOG.md
  packages/core/src/utils/createMap/updateSizeOnReady.ts
  packages/core/src/vuePlugins/vuex.ts
  packages/lib/testMountParameters/CHANGELOG.md
  packages/lib/testMountParameters/index.ts
  packages/plugins/IconMenu/src/components/IconMenu.vue
  packages/plugins/IconMenu/src/store/index.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: bug, refactor

#133 Refactor/types
  packages/types/custom/core.ts
Labels: refactor

#130 refactor: simplify pins plugin
  packages/plugins/Pins/CHANGELOG.md
  packages/plugins/Pins/src/store/index.ts
  packages/plugins/Pins/src/store/state.ts
  packages/plugins/Pins/src/types.ts
Labels: refactor

#134 fix bugs in time frame filter
  packages/plugins/Filter/CHANGELOG.md
  packages/plugins/Filter/src/utils/updateFeatureVisibility.ts
Labels: bug

#135 fix GeoLocation failing map init on Safari<16
  packages/plugins/GeoLocation/CHANGELOG.md
  packages/plugins/GeoLocation/src/store/actions.ts
Labels: bug
