Repository Dataport/polar, pull requests merged in 2024-02, with the labels that each got.

#98 roll back incomplete attribution changes
  packages/plugins/Attributions/CHANGELOG.md
  packages/plugins/Attributions/README.md
  packages/plugins/Attributions/src/utils/lib.ts
Labels: bug

#97 fix pin colour in DISH
  packages/clients/dish/CHANGELOG.md
  packages/clients/dish/src/mapConfig.ts
Labels: bug

#96 fix markers being lost on reclicks
  packages/clients/dish/CHANGELOG.md
  packages/clients/dish/src/plugins/Gfi/Content.vue
  packages/components/CHANGELOG.md
  packages/components/MoveHandle.vue
  packages/core/CHANGELOG.md
  packages/core/src/components/MapContainer.vue
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/src/components/Feature.vue
  packages/plugins/Gfi/src/components/Gfi.vue
  packages/plugins/Gfi/src/store/actions/index.ts
Labels: bug

#100 deprecate gazetteer implementation
  packages/plugins/AddressSearch/README.md
  packages/plugins/AddressSearch/src/utils/searchMethods/getSearchMethod.ts
Labels: documentation

#91 Feature/generic client and documentation improvement
  .eslintignore
  .github/workflows/publish-pages.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  lerna.json
  package.json
  packages/clients/afm/API.md
  packages/clients/generic/API.md
  packages/clients/generic/CHANGELOG.md
  packages/clients/generic/LICENSE
  packages/clients/generic/README.md
  packages/clients/generic/package.json
  packages/clients/generic/src/polar-client.ts
  packages/clients/generic/tsconfig.json
  packages/clients/generic/vite.config.js
  packages/clients/meldemichel/example/index.html
  packages/clients/meldemichel/example/report.html
  packages/clients/meldemichel/example/single.html
  packages/core/CHANGELOG.md
  packages/core/src/index.ts
  packages/plugins/Filter/CHANGELOG.md
  packages/plugins/Filter/src/utils/updateFeatureVisibility.ts
  pages/assets/iceberg.svg
  pages/assets/iceberg_icon.svg
  pages/assets/iframe-resizer/LICENSE
  pages/assets/iframe-resizer/README.md
  pages/assets/iframe-resizer/js/iframeResizer.contentWindow.js
  pages/assets/iframe-resizer/js/iframeResizer.js
  pages/assets/landessymbole/bremen.svg
  pages/assets/landessymbole/hamburg.svg
  pages/assets/landessymbole/sachsen-anhalt.svg
  pages/assets/landessymbole/schleswig-holstein.svg
  pages/assets/landessymbole/sources.md
  pages/assets/manypixels-decentralized.svg
  pages/assets/manypixels-legal.svg
  pages/assets/manypixels-map.svg
  pages/assets/manypixels-mobile.svg
  pages/assets/manypixels-puzzle.svg
  pages/assets/maps_pin.jpg
  pages/assets/polar-architecture.png
  pages/assets/polar-outer-architecture.png
  pages/assets/sources.md
  pages/documentation.html
  pages/examples/address.html
  pages/examples/draw.html
  pages/examples/gfi.html
  pages/examples/layer.html
  pages/examples/locales.html
  pages/examples/orientation.html
  pages/examples/render.js
  pages/index.html
  pages/mvp.css
  pages/package.json
  pages/vite.config.js
  scripts/buildPages.sh
  scripts/makeDocs.js
Labels: documentation, enhancement

#106 improve mobile docs view
  pages/documentation.html
  pages/index.html
  pages/mobile.css
Labels: documentation, enhancement

#105 add noscript advisory
  packages/clients/afm/API.md
  packages/clients/afm/example/index.html
  packages/clients/afm/example/prod-example.html
  packages/clients/dish/src/index.html
  packages/clients/generic/API.md
  packages/clients/meldemichel/API.md
  packages/clients/meldemichel/src/html/index.html
  packages/clients/meldemichel/src/index.html
  packages/clients/snowbox/src/index.html
Labels: documentation, enhancement

#109 fix type to allow custom strings for custom methods
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: bug

#107 Refactor/#33 lib get features
  packages/clients/dish/src/utils/navigateToDenkmal.ts
  packages/lib/getFeatures/CHANGELOG.md
  packages/lib/getFeatures/gazetteer/parse.ts
  packages/lib/getFeatures/types.ts
  packages/lib/getFeatures/wfs/buildWfsFilter.ts
  packages/lib/getFeatures/wfs/getFeatureTitleFromPattern.ts
  packages/lib/getFeatures/wfs/index.ts
  packages/lib/getFeatures/wfs/match.ts
Labels: enhancement, refactor

#114 add optional i18n for feature titles
  packages/plugins/AddressSearch/CHANGELOG.md
  packages/plugins/AddressSearch/src/components/Results.vue
Labels: enhancement

#116 add vector source getter to draw plugin
  packages/plugins/Draw/src/store/index.ts
Labels: enhancement
