Repository Dataport/polar, pull requests merged in 2024-01, with the labels that each got.

#57 Update attributions position in Meldemichel
  packages/clients/meldemichel/CHANGELOG.md
  packages/clients/meldemichel/src/addPlugins.ts
  packages/clients/meldemichel/src/utils/createMenus.ts
  packages/plugins/AddressSearch/CHANGELOG.md
  packages/plugins/AddressSearch/src/components/AddressSearch.vue
  packages/plugins/Scale/CHANGELOG.md
  packages/plugins/Scale/src/components/Scale.vue
Labels: bug, enhancement

#70 Refactor actionButton handling to fix gfi switch buttons issue
  packages/clients/dish/src/plugins/Gfi/Content.vue
  packages/clients/meldemichel/src/plugins/Gfi/Feature.vue
  packages/core/CHANGELOG.md
  packages/core/src/components/MapContainer.vue
  packages/core/src/vuePlugins/vuex.ts
  packages/lib/createTestMountParameters/CHANGELOG.md
  packages/lib/createTestMountParameters/index.ts
  packages/plugins/Gfi/src/components/Gfi.vue
  packages/plugins/Gfi/src/store/getInitialState.ts
  packages/plugins/Gfi/src/types.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: bug, refactor

#69 Fix issue of undefined content in meldemichel gfi on narrow devices
  packages/clients/meldemichel/CHANGELOG.md
  packages/clients/meldemichel/src/plugins/Gfi/Feature.vue
Labels: bug

#74 fix gfi window navigation style to match neighbouring elements
  packages/clients/meldemichel/CHANGELOG.md
  packages/clients/meldemichel/src/plugins/Gfi/ActionButtons.vue
Labels: enhancement

#71 Fix linting setup for vue files
  .eslintrc.json
  package-lock.json
  package.json
  packages/plugins/AddressSearch/src/components/AddressSearch.vue
  packages/plugins/Attributions/src/components/AttributionContent.vue
  packages/plugins/Gfi/src/components/List.vue
Labels: bug

#75 add information to docs on how to override locales
  packages/core/README.md
Labels: documentation

#76 improve focus highlighting on WFS List
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/src/components/List.vue
Labels: enhancement

#59 Set minHeight back to 0.2 to have content changes always be visible
  packages/components/CHANGELOG.md
  packages/components/MoveHandle.vue
Labels: bug

#78 document plugin order requirements
  packages/plugins/Attributions/README.md
  packages/plugins/Gfi/README.md
  packages/plugins/Pins/README.md
  packages/plugins/ReverseGeocoder/README.md
Labels: documentation

#83 fix update attribution on leaving layer resolution
  packages/plugins/Attributions/CHANGELOG.md
  packages/plugins/Attributions/src/store/index.ts
Labels: bug

#77 Feature/#65 feature changer after click to feature list sometimes missing
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/core/src/vuePlugins/actions/useExtendedMasterportalapiMarkers/center.ts
  packages/core/src/vuePlugins/actions/useExtendedMasterportalapiMarkers/getFeaturesCluster.ts
  packages/core/src/vuePlugins/actions/useExtendedMasterportalapiMarkers/index.ts
  packages/core/src/vuePlugins/vuex.ts
  packages/lib/getCluster/CHANGELOG.md
  packages/lib/getCluster/LICENSE
  packages/lib/getCluster/README.md
  packages/lib/getCluster/index.ts
  packages/lib/getCluster/package.json
  packages/lib/getCluster/tsconfig.json
  packages/lib/getCluster/vite.config.js
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/package.json
  packages/plugins/Gfi/src/components/List.vue
  packages/plugins/Gfi/src/store/actions/index.ts
  packages/plugins/Gfi/src/store/getters.ts
  packages/plugins/Gfi/src/types.ts
Labels: enhancement

#82 remove tooltips on touch and pen events
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/README.md
  packages/plugins/Gfi/src/store/actions/index.ts
Labels: enhancement

#79 refactor some overly long functions and files
  packages/clients/dish/src/addPlugins.ts
  packages/clients/dish/src/plugins/Modal/Hints.vue
  packages/clients/dish/src/utils/autocomplete.ts
  packages/clients/dish/src/utils/extendGfi.ts
  packages/clients/dish/src/utils/search.ts
  packages/clients/meldemichel/src/addPlugins.ts
  packages/clients/meldemichel/src/mapConfigurations.ts
  packages/clients/snowbox/src/addPlugins.ts
  packages/types/custom/core.ts
Labels: refactor

#84 refactor MapContainer.vue
  packages/core/src/components/MapContainer.vue
  packages/core/src/types.ts
  packages/core/src/vuePlugins/vuex.ts
Labels: refactor

#81 implement hatchable markers
  packages/core/CHANGELOG.md
  packages/core/README.md
  packages/core/src/utils/markers/hatches.ts
  packages/core/src/utils/markers/index.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#87 add missing aria label
  packages/plugins/Fullscreen/CHANGELOG.md
  packages/plugins/Fullscreen/src/components/Fullscreen.vue
Labels: bug

#86 Refactor/#80 draw createinteractions
  packages/plugins/Draw/src/store/actions.ts
  packages/plugins/Draw/src/store/createInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/createDeleteInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/createModifyInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/createTextInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/index.ts
  packages/plugins/Draw/src/types.ts
Labels: refactor

#88 Refactor/#41 standardize error messages
  packages/clients/afm/example/polar-example.js
  packages/clients/dish/src/utils/autocomplete.ts
  packages/clients/dish/src/utils/extendGfi.ts
  packages/clients/dish/src/utils/navigateToDenkmal.ts
  packages/clients/dish/src/utils/search.ts
  packages/clients/meldemichel/src/plugins/AfmButton/AfmButton.vue
  packages/clients/meldemichel/src/polar-client.ts
  packages/clients/meldemichel/src/utils/enableClustering.ts
  packages/core/src/monkeyHeaderLoader.ts
  packages/core/src/storeModules/capabilities.ts
  packages/core/src/utils/addPlugins.ts
  packages/core/src/utils/createMap/makeShadowRoot.ts
  packages/core/src/utils/createMap/pullPolarStyleToShadow.ts
  packages/core/src/utils/createMap/pullVuetifyStyleToShadow.ts
  packages/core/src/utils/createMap/updateSizeOnReady.ts
  packages/core/src/utils/markers/hatches.ts
  packages/core/src/utils/markers/index.ts
  packages/core/src/vuePlugins/vuex.ts
  packages/lib/getFeatures/wfs/index.ts
  packages/lib/passesBoundaryCheck/index.ts
  packages/plugins/AddressSearch/src/store/actions.ts
  packages/plugins/AddressSearch/src/utils/searchMethods/getSearchMethod.ts
  packages/plugins/AddressSearch/src/utils/searchMethods/mpapi.ts
  packages/plugins/Export/src/store/actions.ts
  packages/plugins/Fullscreen/src/components/Fullscreen.vue
  packages/plugins/GeoLocation/src/store/actions.ts
  packages/plugins/Gfi/src/components/List.vue
  packages/plugins/Gfi/src/store/actions/index.ts
  packages/plugins/Gfi/src/store/getters.ts
  packages/plugins/Gfi/src/utils/listableLayersFilter.ts
  packages/plugins/Gfi/src/utils/requestGfiWms.ts
  packages/plugins/LayerChooser/src/store/index.ts
  packages/plugins/Pins/src/store/index.ts
  packages/plugins/ReverseGeocoder/src/store/index.ts
  packages/plugins/Scale/src/utils/getDpi.ts
Labels: refactor

#89 Refactor/#33 core
  packages/core/src/vuePlugins/actions/checkServiceAvailability.ts
  packages/core/src/vuePlugins/vuex.ts
Labels: refactor

#85 Slightly enlarge markers for easier usage on mobile devices
  packages/clients/meldemichel/src/utils/enableClustering.ts
  packages/core/CHANGELOG.md
  packages/core/README.md
  packages/core/src/utils/markers/index.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#90 remove wildcard on street search
  arcana.md
  package.json
  packages/clients/meldemichel/CHANGELOG.md
  scripts/overrideMasterportalapi.js
Labels: bug

#92 Fix keyboard navigation of address search
  packages/plugins/AddressSearch/CHANGELOG.md
  packages/plugins/AddressSearch/src/components/Results.vue
Labels: bug

#93 Fix typescript setup
  @types/vue-shims/index.d.ts
  @types/vue-shims/json-loader.d.ts
  @types/vue-shims/png-loader.d.ts
  @types/vue-shims/shims-tsx.d.ts
  @types/vue-shims/shims-vue.d.ts
  @types/vue-shims/tsconfig.json
  packages/types/vue-shims/tsconfig.json
  tsconfig.json
Labels: enhancement
