Repository Dataport/polar, pull requests merged in 2025-02, with the labels that each got.

#230 change git URLs to recommended format
  packages/clients/afm/package.json
  packages/clients/dish/package.json
  packages/clients/generic/package.json
  packages/clients/meldemichel/package.json
  packages/clients/textLocator/package.json
  packages/components/package.json
  packages/core/package.json
  packages/lib/getCluster/package.json
  packages/lib/getFeatures/package.json
  packages/lib/idx/package.json
  packages/lib/invisibleStyle/package.json
  packages/lib/passesBoundaryCheck/package.json
  packages/lib/testMountParameters/package.json
  packages/lib/tooltip/package.json
  packages/plugins/AddressSearch/package.json
  packages/plugins/Attributions/package.json
  packages/plugins/Draw/package.json
  packages/plugins/Export/package.json
  packages/plugins/Fullscreen/package.json
  packages/plugins/GeoLocation/package.json
  packages/plugins/Gfi/package.json
  packages/plugins/IconMenu/package.json
  packages/plugins/LayerChooser/package.json
  packages/plugins/Legend/package.json
  packages/plugins/LoadingIndicator/package.json
  packages/plugins/Pins/package.json
  packages/plugins/ReverseGeocoder/package.json
  packages/plugins/Scale/package.json
  packages/plugins/Toast/package.json
  packages/plugins/Zoom/package.json
  packages/types/custom/package.json
Labels: documentation

#216 add locale register to docs
  package-lock.json
  package.json
  packages/clients/dish/src/language.ts
  packages/clients/dish/src/mapConfig.ts
  packages/clients/textLocator/src/language.ts
  packages/clients/textLocator/src/mapConfig.ts
  packages/core/README.md
  packages/core/src/i18n/index.ts
  packages/core/src/language.ts
  packages/core/src/language/locales/de.ts
  packages/core/src/language/locales/en.ts
  packages/core/src/utils/createMap/index.ts
  scripts/makeDocs.ts
Labels: documentation

#226 Update @masterportal/masterportalapi to v2.45.0 and thus ol to v10.3.1
  jest.config.ts
  package-lock.json
  package.json
  packages/clients/dish/CHANGELOG.md
  packages/clients/dish/package.json
  packages/clients/meldemichel/src/polar-client.ts
  packages/clients/textLocator/CHANGELOG.md
  packages/clients/textLocator/package.json
  packages/clients/textLocator/src/plugins/GeometrySearch/utils/vectorDisplay.ts
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/core/src/utils/setupStyling.ts
  packages/core/src/vuePlugins/actions/useExtendedMasterportalapiMarkers/index.ts
  packages/core/src/vuePlugins/actions/useExtendedMasterportalapiMarkers/setLayerId.ts
  packages/lib/getCluster/CHANGELOG.md
  packages/lib/getCluster/package.json
  packages/lib/getFeatures/CHANGELOG.md
  packages/lib/getFeatures/package.json
  packages/lib/invisibleStyle/CHANGELOG.md
  packages/lib/invisibleStyle/package.json
  packages/lib/passesBoundaryCheck/CHANGELOG.md
  packages/lib/passesBoundaryCheck/index.ts
  packages/lib/passesBoundaryCheck/package.json
  packages/plugins/AddressSearch/CHANGELOG.md
  packages/plugins/AddressSearch/package.json
  packages/plugins/Attributions/CHANGELOG.md
  packages/plugins/Attributions/package.json
  packages/plugins/Draw/CHANGELOG.md
  packages/plugins/Draw/package.json
  packages/plugins/Draw/src/store/createInteractions/createDeleteInteractions.ts
  packages/plugins/Draw/src/types.ts
  packages/plugins/Filter/CHANGELOG.md
  packages/plugins/Filter/package.json
  packages/plugins/GeoLocation/CHANGELOG.md
  packages/plugins/GeoLocation/package.json
  packages/plugins/GeoLocation/src/types.ts
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/package.json
  packages/plugins/Gfi/src/store/actions/debouncedGfiRequest.ts
  packages/plugins/Gfi/src/utils/displayFeatureLayer.ts
  packages/plugins/Gfi/src/utils/renderFeatures.ts
  packages/plugins/Gfi/src/utils/requestGfiGeoJson.ts
  packages/plugins/LayerChooser/CHANGELOG.md
  packages/plugins/LayerChooser/package.json
  packages/plugins/Pins/CHANGELOG.md
  packages/plugins/Pins/package.json
  packages/plugins/Pins/src/store/index.ts
  packages/plugins/ReverseGeocoder/CHANGELOG.md
  packages/plugins/ReverseGeocoder/package.json
  packages/plugins/Scale/CHANGELOG.md
  packages/plugins/Scale/package.json
Labels: versioning

#220 DiPlanung Client
  package-lock.json
  package.json
  packages/clients/diplan/API.md
  packages/clients/diplan/CHANGELOG.md
  packages/clients/diplan/LICENSE
  packages/clients/diplan/README.md
  packages/clients/diplan/assets/README.md
  packages/clients/diplan/example/config.js
  packages/clients/diplan/example/index.html
  packages/clients/diplan/example/prod-example.html
  packages/clients/diplan/example/services.js
  packages/clients/diplan/example/setup.js
  packages/clients/diplan/example/style.css
  packages/clients/diplan/package.json
  packages/clients/diplan/src/index.css
  packages/clients/diplan/src/plugins/Gfi/Content.vue
  packages/clients/diplan/src/plugins/Gfi/index.ts
  packages/clients/diplan/src/polar-client.ts
  packages/clients/diplan/vite.config.js
  packages/core/CHANGELOG.md
  packages/core/README.md
  packages/lib/testMountParameters/index.ts
  packages/plugins/Attributions/CHANGELOG.md
  packages/plugins/Attributions/README.md
  packages/plugins/Attributions/src/components/AttributionButton.vue
  packages/plugins/Attributions/src/store/index.ts
  packages/plugins/Attributions/src/types.ts
  packages/plugins/Legend/CHANGELOG.md
  packages/plugins/Legend/README.md
  packages/plugins/Legend/src/components/Legend.vue
  packages/plugins/Legend/src/index.ts
  packages/plugins/Zoom/CHANGELOG.md
  packages/plugins/Zoom/README.md
  packages/plugins/Zoom/src/components/Zoom.vue
  packages/plugins/Zoom/src/store/index.ts
  packages/plugins/Zoom/src/types.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
  pages/documentation.html
  scripts/buildPages.sh
  scripts/precompileCss.js
  scripts/precompileSvg.js
Labels: enhancement

#232 gfi: Add missing commas
  packages/plugins/Gfi/README.md
Labels: documentation

#228 fix that drawings on top of each other were glued
  packages/plugins/Draw/CHANGELOG.md
  packages/plugins/Draw/src/store/actions.ts
  packages/plugins/Draw/src/store/createInteractions/createModifyInteractions.ts
Labels: bug

#231 add export and example to diplan client
  package-lock.json
  packages/clients/diplan/example/config.js
  packages/clients/diplan/example/index.html
  packages/clients/diplan/example/prod-example.html
  packages/clients/diplan/example/setup.js
  packages/clients/diplan/example/style.css
  packages/clients/diplan/package.json
  packages/clients/diplan/src/polar-client.ts
Labels: documentation, enhancement

#234 Change mail to new shorter alias
  .github/workflows/publish-packages.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  package.json
  packages/clients/afm/package.json
  packages/clients/diplan/package.json
  packages/clients/dish/package.json
  packages/clients/generic/package.json
  packages/clients/meldemichel/package.json
  packages/clients/snowbox/package.json
  packages/clients/textLocator/package.json
  packages/components/package.json
  packages/core/package.json
  packages/lib/getCluster/package.json
  packages/lib/getFeatures/package.json
  packages/lib/idx/package.json
  packages/lib/invisibleStyle/package.json
  packages/lib/passesBoundaryCheck/package.json
  packages/lib/testMountParameters/package.json
  packages/lib/tooltip/package.json
  packages/plugins/AddressSearch/package.json
  packages/plugins/Attributions/package.json
  packages/plugins/Draw/package.json
  packages/plugins/Export/package.json
  packages/plugins/Filter/package.json
  packages/plugins/Fullscreen/package.json
  packages/plugins/GeoLocation/package.json
  packages/plugins/Gfi/package.json
  packages/plugins/IconMenu/package.json
  packages/plugins/LayerChooser/package.json
  packages/plugins/Legend/package.json
  packages/plugins/LoadingIndicator/package.json
  packages/plugins/Pins/package.json
  packages/plugins/ReverseGeocoder/package.json
  packages/plugins/Scale/package.json
  packages/plugins/Toast/package.json
  packages/plugins/Zoom/package.json
  packages/types/custom/package.json
  pages/documentation.html
  pages/index.html
  pages/package.json
  security.md
Labels: refactor

#233 Adjust isDrawing so directSelect works even when multiSelect is used
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/src/store/actions/setupMultiSelection.ts
Labels: bug

#235 add translate mode to draw
  packages/plugins/Draw/CHANGELOG.md
  packages/plugins/Draw/src/locales.ts
  packages/plugins/Draw/src/store/actions.ts
  packages/plugins/Draw/src/store/createInteractions/createModifyInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/createTranslateInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/index.ts
  packages/plugins/Draw/src/store/createInteractions/localSelector.ts
  packages/plugins/Draw/src/store/index.ts
  packages/plugins/Draw/src/types.ts
Labels: enhancement

#225 Bgw initial client
  package-lock.json
  package.json
  packages/clients/bgw/CHANGELOG.md
  packages/clients/bgw/LICENSE
  packages/clients/bgw/README.md
  packages/clients/bgw/package.json
  packages/clients/bgw/src/addPlugins.ts
  packages/clients/bgw/src/html/index.html
  packages/clients/bgw/src/index.html
  packages/clients/bgw/src/mapConfiguration.ts
  packages/clients/bgw/src/polar-client.ts
  packages/clients/bgw/src/services.ts
  packages/clients/bgw/src/style.json
  packages/clients/bgw/src/utils/badestellenSearch.ts
  packages/clients/bgw/tsconfig.json
  packages/clients/bgw/vite.config.js
  pages/documentation.html
  scripts/buildPages.sh
Labels: enhancement

#236 extend diplan example
  packages/clients/diplan/example/config.js
  packages/clients/diplan/example/index.html
  packages/clients/diplan/example/prod-example.html
  packages/clients/diplan/example/setup.js
  packages/clients/diplan/example/style.css
  packages/clients/diplan/src/polar-client.ts
Labels: documentation

#238 rename global diplan client to technical name
  packages/clients/diplan/example/prod-example.html
  packages/clients/diplan/vite.config.js
Labels: refactor

#237 Feature/add snap to mode to draw
  package-lock.json
  packages/clients/diplan/example/config.js
  packages/clients/diplan/example/services.js
  packages/clients/diplan/package.json
  packages/clients/diplan/src/polar-client.ts
  packages/core/README.md
  packages/plugins/Draw/CHANGELOG.md
  packages/plugins/Draw/README.md
  packages/plugins/Draw/src/store/actions.ts
  packages/plugins/Draw/src/store/createInteractions/createDrawInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/createModifyInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/createTextInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/createTranslateInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/getSnaps.ts
  packages/plugins/Draw/src/store/createInteractions/index.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#241 Allow layers that have singleTile: true set to be used for gfi requests
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/src/types.ts
  packages/plugins/Gfi/src/utils/requestGfi.ts
Labels: bug

#240 fix image visibility in chromium snowbox example
  packages/clients/snowbox/src/html/index.html
  packages/clients/snowbox/src/index.html
Labels: bug

#244 add xtrasse to diplan client
  packages/clients/diplan/example/config.js
  packages/clients/diplan/example/services.js
Labels: enhancement

#239 remove pan tooltip during drag interaction
  packages/core/CHANGELOG.md
  packages/core/README.md
  packages/core/src/components/MapContainer.vue
  packages/plugins/Draw/CHANGELOG.md
  packages/plugins/Draw/src/store/createInteractions/createModifyInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/createTranslateInteractions.ts
Labels: bug

#246 Feature/bgw custom search function
  packages/clients/bgw/src/addPlugins.ts
  packages/clients/bgw/src/mapConfiguration.ts
  packages/clients/bgw/src/utils/badestellenSearch.ts
Labels: enhancement

#248 Feature/add download button in bgw gfi
  packages/clients/bgw/README.md
  packages/clients/bgw/src/addPlugins.ts
  packages/clients/bgw/src/mapConfiguration.ts
  packages/clients/bgw/src/plugins/Gfi/ActionButton.vue
  packages/clients/bgw/src/plugins/Gfi/Content.vue
Labels: enhancement

#250 Feature/highlight expansion by clicking on bathing area
  package-lock.json
  package.json
  packages/clients/bgw/README.md
  packages/clients/bgw/package.json
  packages/clients/bgw/src/mapConfiguration.ts
  packages/clients/bgw/src/plugins/Gfi/Content.vue
  packages/clients/bgw/src/polar-client.ts
  packages/clients/bgw/src/store/module.ts
  scripts/buildPages.sh
Labels: enhancement

#251 prepare diplan example folder for multiple prod instances
  package.json
  packages/clients/diplan/API.md
  packages/clients/diplan/example/README.md
  packages/clients/diplan/example/dev/config.js
  packages/clients/diplan/example/dev/index.html
  packages/clients/diplan/example/dev/setup.js
  packages/clients/diplan/example/overview.html
  packages/clients/diplan/example/polar-ui/config.js
  packages/clients/diplan/example/polar-ui/index.html
  packages/clients/diplan/example/polar-ui/setup.js
  packages/clients/diplan/example/style.css
  packages/clients/diplan/vite.config.js
Labels: refactor
