Repository Dataport/polar, pull requests merged in 2025-01, with the labels that each got.

#210 Use correct title hierarchy in several readme files
  packages/plugins/Draw/README.md
  packages/plugins/Export/README.md
  packages/plugins/Filter/README.md
  packages/plugins/GeoLocation/README.md
  packages/plugins/Gfi/README.md
Labels: bug

#192 Fix issue regarding not being able to separately modify snapped features
  e2e/draw.spec.ts
  packages/plugins/Draw/src/store/createInteractions/createModifyInteractions.ts
Labels: bug

#207 Feature/gfi set feature information
  packages/clients/snowbox/src/exampleFeatureInformation.ts
  packages/clients/snowbox/src/index.html
  packages/clients/snowbox/src/polar-client.ts
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/README.md
  packages/plugins/Gfi/src/store/actions/debouncedGfiRequest.ts
  packages/plugins/Gfi/src/store/actions/index.ts
  packages/plugins/Gfi/src/store/actions/setup.ts
  packages/plugins/Gfi/src/types.ts
  packages/plugins/Gfi/src/utils/filterFeatures.ts
  packages/plugins/Gfi/src/utils/renderFeatures.ts
  packages/plugins/Gfi/tests/filterFeatures.spec.ts
  packages/plugins/Gfi/tests/sortFeatures.spec.ts
Labels: enhancement, refactor

#218 fix tooltip font family
  packages/core/CHANGELOG.md
  packages/core/src/utils/createMap/pullVuetifyStyleToShadow.ts
Labels: bug

#214 add embedded scenario for meldemichel
  packages/clients/meldemichel/API.md
  packages/clients/meldemichel/example/complete_embedded.html
  packages/clients/meldemichel/example/index.html
Labels: documentation

#213 add stadtwald layer for Meldemichel clerks
  packages/clients/meldemichel/API.md
  packages/clients/meldemichel/CHANGELOG.md
  packages/clients/meldemichel/src/index.html
  packages/clients/meldemichel/src/language.ts
  packages/clients/meldemichel/src/mapConfigurations.ts
  packages/clients/meldemichel/src/polar-client.ts
  packages/clients/meldemichel/src/store/module.ts
  packages/clients/meldemichel/src/types.ts
Labels: enhancement

#124 Feature/add measure tool
  e2e/draw.spec.ts
  package-lock.json
  packages/clients/snowbox/src/mapConfiguration.ts
  packages/core/CHANGELOG.md
  packages/core/src/components/RadioCard.vue
  packages/core/src/components/index.ts
  packages/core/src/index.ts
  packages/plugins/Draw/CHANGELOG.md
  packages/plugins/Draw/README.md
  packages/plugins/Draw/package.json
  packages/plugins/Draw/src/components/Draw.vue
  packages/plugins/Draw/src/language.ts
  packages/plugins/Draw/src/store/actions.ts
  packages/plugins/Draw/src/store/createInteractions/createDeleteInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/createModifyInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/index.ts
  packages/plugins/Draw/src/store/index.ts
  packages/plugins/Draw/src/types.ts
  packages/plugins/Draw/src/utils/createDrawStyle.ts
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/src/store/actions/setup.ts
  packages/plugins/Pins/src/store/index.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#219 Fix interface extendedMasterportalapiMarkers to align with documentation
  packages/core/README.md
  packages/core/src/vuePlugins/actions/useExtendedMasterportalapiMarkers/index.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: bug

#222 Do not break themes of external vuetify apps
  packages/core/CHANGELOG.md
  packages/core/src/utils/createMap/index.ts
Labels: bug

#224 Change order of layers to fix overlapping layers
  packages/clients/snowbox/src/mapConfiguration.ts
Labels: bug

#211 Extend multi selection by adding new mode "circle"
  packages/clients/snowbox/src/mapConfiguration.ts
  packages/plugins/Draw/src/store/createInteractions/createTextInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/index.ts
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/README.md
  packages/plugins/Gfi/src/store/actions/index.ts
  packages/plugins/Gfi/src/store/actions/setup.ts
  packages/plugins/Gfi/src/store/actions/setupMultiSelection.ts
  packages/plugins/Pins/CHANGELOG.md
  packages/plugins/Pins/src/store/index.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement, refactor
