Repository Dataport/polar, pull requests merged in 2025-03, with the labels that each got.

#208 Dish intern
  @types/i18next.d.ts
  package-lock.json
  packages/clients/dish/CHANGELOG.md
  packages/clients/dish/README.md
  packages/clients/dish/package.json
  packages/clients/dish/src/addPlugins.ts
  packages/clients/dish/src/colors.ts
  packages/clients/dish/src/enums.ts
  packages/clients/dish/src/html/index.html
  packages/clients/dish/src/index.html
  packages/clients/dish/src/mapConfig.ts
  packages/clients/dish/src/mapConfigurations/attributionsConfig.ts
  packages/clients/dish/src/mapConfigurations/layerConfigIntern.ts
  packages/clients/dish/src/mapConfigurations/mapConfig.ts
  packages/clients/dish/src/mapConfigurations/mapConfigExtern.ts
  packages/clients/dish/src/mapConfigurations/mapConfigIntern.ts
  packages/clients/dish/src/mapConfigurations/searchConfigParams.ts
  packages/clients/dish/src/plugins/DishExportMap/DishExportMap.vue
  packages/clients/dish/src/plugins/DishExportMap/README.md
  packages/clients/dish/src/plugins/DishExportMap/index.ts
  packages/clients/dish/src/plugins/DishExportMap/locales.ts
  packages/clients/dish/src/plugins/Gfi/ContentExtern.vue
  packages/clients/dish/src/plugins/Gfi/ContentIntern.vue
  packages/clients/dish/src/plugins/Gfi/MonumentContent.vue
  packages/clients/dish/src/plugins/Gfi/SharedContent.vue
  packages/clients/dish/src/plugins/Gfi/SwitchButton.vue
  packages/clients/dish/src/plugins/Gfi/index.ts
  packages/clients/dish/src/plugins/Modal/Hints.vue
  packages/clients/dish/src/plugins/Modal/HintsIntern.vue
  packages/clients/dish/src/plugins/Modal/Modal.vue
  packages/clients/dish/src/plugins/Modal/SharedHints.vue
  packages/clients/dish/src/plugins/Modal/locales.ts
  packages/clients/dish/src/plugins/Modal/store.ts
  packages/clients/dish/src/polar-client.ts
  packages/clients/dish/src/services.ts
  packages/clients/dish/src/servicesConstants.ts
  packages/clients/dish/src/servicesIntern.ts
  packages/clients/dish/src/types.ts
  packages/clients/dish/src/utils/autocomplete.ts
  packages/clients/dish/src/utils/denkmalSearchIntern.ts
  packages/clients/dish/src/utils/extendGfi.ts
  packages/clients/dish/src/utils/navigateToDenkmal.ts
  packages/clients/dish/src/utils/prepareGfiDataIntern.ts
  packages/clients/dish/src/utils/zoomToFeatureById.ts
  packages/core/CHANGELOG.md
  packages/core/README.md
  packages/core/src/index.ts
  packages/plugins/AddressSearch/CHANGELOG.md
  packages/plugins/AddressSearch/src/index.ts
  packages/plugins/LayerChooser/CHANGELOG.md
  packages/plugins/LayerChooser/src/locales.ts
Labels: enhancement

#255 Add missing letter in documentation
  packages/plugins/Gfi/README.md
Labels: bug

#262 add screenshot to README.md
  README.md
  pages/assets/polar_example_screenshot.png
Labels: documentation

#252 Prepare Draw overload for DiPlan client
  packages/clients/diplan/example/dev/index.html
  packages/clients/diplan/example/dev/setup.js
  packages/clients/diplan/example/polar-ui/setup.js
  packages/clients/diplan/src/store/geoEditing/cutPolygons.ts
  packages/clients/diplan/src/store/geoEditing/duplicatePolygons.ts
  packages/clients/diplan/src/store/geoEditing/mergePolygons.ts
  packages/clients/diplan/src/store/module.ts
  packages/clients/diplan/src/store/updateState/enrichWithMetaServices.ts
  packages/clients/diplan/src/store/updateState/index.ts
  packages/clients/diplan/src/store/updateState/mergeToMultiGeometries.ts
  packages/clients/diplan/src/store/updateState/validateGeoJson.ts
  packages/clients/diplan/src/types.ts
  packages/plugins/Draw/CHANGELOG.md
  packages/plugins/Draw/README.md
  packages/plugins/Draw/src/index.ts
  packages/plugins/Draw/src/store/actions.ts
  packages/plugins/Draw/src/store/createInteractions/createDrawInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/createModifyInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/createTextInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/createTranslateInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/getSnaps.ts
Labels: enhancement

#264 show cursor pointer on delete interaction
  packages/plugins/Draw/CHANGELOG.md
  packages/plugins/Draw/src/store/actions.ts
  packages/plugins/Draw/src/store/createInteractions/createDeleteInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/index.ts
Labels: enhancement

#263 Feature/diplan merge polygons
  package-lock.json
  packages/clients/diplan/package.json
  packages/clients/diplan/src/store/geoEditing/mergePolygons.ts
  packages/clients/diplan/src/store/module.ts
Labels: enhancement

#265 implement geometry cloning
  packages/clients/diplan/example/dev/index.html
  packages/clients/diplan/example/dev/setup.js
  packages/clients/diplan/src/store/geoEditing/duplicatePolygons.ts
Labels: enhancement

#273 remove peer dependencies from diplan
  package-lock.json
  packages/clients/diplan/package.json
Labels: refactor

#274 unkink and simplify coordinates in diplan client export
  package-lock.json
  packages/clients/diplan/package.json
  packages/clients/diplan/src/store/updateState/index.ts
Labels: enhancement

#249 Feature/secure services
  packages/clients/diplan/API.md
  packages/clients/diplan/example/authentication/index.js
  packages/clients/diplan/example/authentication/validateForm.js
  packages/clients/diplan/example/dev/config.js
  packages/clients/diplan/example/dev/index.html
  packages/clients/diplan/example/dev/setup.js
  packages/clients/diplan/example/services.js
  packages/core/CHANGELOG.md
  packages/core/README.md
  packages/core/src/components/MapContainer.vue
  packages/core/src/utils/createMap/index.ts
  packages/core/src/vuePlugins/actions/addInterceptor.ts
  packages/core/src/vuePlugins/vuex.ts
  packages/lib/testMountParameters/CHANGELOG.md
  packages/lib/testMountParameters/index.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#268 Feature/diplan cut polygon
  package-lock.json
  packages/clients/diplan/package.json
  packages/clients/diplan/src/locales.ts
  packages/clients/diplan/src/store/geoEditing/cutPolygons.ts
  packages/clients/diplan/src/store/geoEditing/cutPolygons/cutlery.ts
  packages/clients/diplan/src/store/geoEditing/cutPolygons/index.ts
  packages/clients/diplan/src/store/geoEditing/cutPolygons/makeDraw.ts
  packages/clients/diplan/src/store/geoEditing/cutPolygons/style.ts
  packages/clients/diplan/src/store/geoEditing/cutPolygons/types.ts
Labels: enhancement

#275 make export programmatic only
  packages/clients/diplan/example/dev/config.js
  packages/clients/diplan/example/dev/index.html
  packages/clients/diplan/example/dev/setup.js
  packages/clients/diplan/example/polar-ui/config.js
  packages/clients/diplan/example/polar-ui/index.html
  packages/clients/diplan/example/polar-ui/setup.js
Labels: enhancement

#279 Feature/diplan bkg
  packages/clients/diplan/example/dev/config.js
  packages/clients/diplan/example/polar-ui/config.js
Labels: enhancement

#278 disable automatic full interaction end on first end
  packages/clients/diplan/example/polar-ui/index.html
  packages/clients/diplan/example/polar-ui/setup.js
  packages/clients/diplan/src/store/geoEditing/cutPolygons/index.ts
  packages/clients/diplan/src/store/geoEditing/duplicatePolygons.ts
  packages/clients/diplan/src/store/geoEditing/mergePolygons.ts
  packages/plugins/Draw/src/store/createInteractions/createLassoInteractions.ts
Labels: enhancement

#281 fix minZoom for layers to work from minZoom on
  packages/core/CHANGELOG.md
  packages/core/src/components/MapContainer.vue
  packages/core/src/utils/mapZoomOffset.ts
  packages/plugins/LayerChooser/CHANGELOG.md
  packages/plugins/LayerChooser/README.md
Labels: bug

#285 Fix issue of addInterceptor not having access yet to the regex
  packages/core/src/components/MapContainer.vue
  packages/core/src/vuePlugins/actions/addInterceptor.ts
Labels: bug

#282 prevent snapping to invisible layers
  packages/plugins/Draw/CHANGELOG.md
  packages/plugins/Draw/src/store/createInteractions/getSnaps.ts
Labels: bug

#284 fix duplicate polygon style
  packages/clients/diplan/src/store/geoEditing/duplicatePolygons.ts
Labels: bug

#280 Feature/bkg in diplan UI
  packages/clients/diplan/example/diplan-ui-one/config.js
  packages/clients/diplan/example/diplan-ui-two/config.js
Labels: enhancement

#267 Feature/link button
  packages/clients/diplan/API.md
  packages/clients/diplan/example/diplan-ui-one/config.js
  packages/clients/diplan/example/diplan-ui-two/config.js
  packages/clients/diplan/src/addPlugins.ts
  packages/clients/diplan/src/config.js
  packages/clients/diplan/src/locales.ts
  packages/clients/diplan/src/plugins/LinkButton/LinkButton.vue
  packages/clients/diplan/src/plugins/LinkButton/index.ts
  packages/clients/diplan/src/types.ts
Labels: enhancement

#271 Feature/small diplan example
  packages/clients/diplan/example/diplan-ui-one/config.js
  packages/clients/diplan/example/diplan-ui-small/config.js
  packages/clients/diplan/example/diplan-ui-small/index.html
  packages/clients/diplan/example/diplan-ui-small/setup.js
  packages/clients/diplan/example/diplan-ui-two/config.js
  packages/clients/diplan/example/overview.html
  packages/clients/diplan/src/addPlugins.ts
  packages/clients/diplan/src/locales.ts
Labels: documentation, enhancement

#286 fix arrow navigation in radio groups
  arcana.md
  packages/clients/textLocator/CHANGELOG.md
  packages/clients/textLocator/src/plugins/GeometrySearch/components/DrawMode.vue
  packages/core/CHANGELOG.md
  packages/core/src/components/RadioCard.vue
  packages/plugins/Filter/CHANGELOG.md
  packages/plugins/Filter/src/components/Filter.vue
  packages/plugins/LayerChooser/CHANGELOG.md
  packages/plugins/LayerChooser/src/components/Selection.vue
Labels: bug, accessibility

#287 Add a layer group for xplan layers in @polar/client-diplan
  packages/clients/diplan/example/diplan-ui-one/config.js
  packages/clients/diplan/example/diplan-ui-two/config.js
  packages/clients/diplan/src/config.js
  packages/clients/diplan/src/locales.ts
  packages/clients/diplan/src/plugins/LayerChooser/LayerChooser.vue
  packages/clients/diplan/src/plugins/LayerChooser/LayerWrapper.vue
Labels: enhancement

#289 Update overview.html
  packages/clients/diplan/example/overview.html
Labels: documentation

#292 Fix/diplan spa rerender
  packages/clients/diplan/API.md
  packages/clients/diplan/CHANGELOG.md
  packages/clients/diplan/example/diplan-ui-one/index.html
  packages/clients/diplan/example/diplan-ui-one/setup.js
  packages/clients/diplan/example/diplan-ui-small/setup.js
  packages/clients/diplan/src/polar-client.ts
  packages/core/CHANGELOG.md
  packages/core/src/index.ts
  packages/core/src/utils/addPlugins.ts
  packages/core/src/vuePlugins/vuex.ts
Labels: bug

#291 add nested e2e test setup
  .github/workflows/run-tests.yml
  .gitignore
  e2e/draw.spec.ts
  e2e/utils/draw.ts
  e2e/utils/package.json
  jest.config.ts
  package.json
  packages/clients/diplan/e2e/draw.spec.ts
  packages/clients/diplan/e2e/utils/openDiplan.ts
  packages/clients/diplan/example/index.html
  packages/clients/diplan/playwright.config.ts
  playwright.config.ts
Labels: testing

#293 Feature/additional layer chooser groups
  packages/clients/diplan/CHANGELOG.md
  packages/clients/diplan/src/plugins/LayerChooser/LayerChooser.vue
  packages/plugins/LayerChooser/CHANGELOG.md
  packages/plugins/LayerChooser/README.md
  packages/plugins/LayerChooser/src/components/Selection.vue
  packages/plugins/LayerChooser/src/store/index.ts
  packages/plugins/LayerChooser/src/types.ts
  packages/plugins/LayerChooser/src/utils/getBackgroundsAndMasks.ts
  packages/types/custom/core.ts
Labels: enhancement

#294 Feature/add options example for xplan
  packages/clients/diplan/example/diplan-ui-one/config.js
  packages/clients/diplan/example/diplan-ui-two/config.js
  packages/clients/diplan/example/polar-ui/config.js
  packages/clients/diplan/src/config.js
  packages/clients/diplan/src/plugins/LayerChooser/LayerChooser.vue
  packages/plugins/LayerChooser/CHANGELOG.md
  packages/plugins/LayerChooser/src/locales.ts
Labels: enhancement

#295 Feature/add more layers to diplan
  packages/clients/diplan/CHANGELOG.md
  packages/clients/diplan/example/diplan-ui-one/config.js
  packages/clients/diplan/example/diplan-ui-two/config.js
  packages/clients/diplan/example/services.js
  packages/clients/diplan/src/config.js
  packages/clients/diplan/src/plugins/LayerChooser/LayerChooser.vue
Labels: enhancement
