Repository Dataport/polar, pull requests merged in 2025-04, with the labels that each got.

#288 activate all e2e tests, active mobile e2e
  e2e/draw.spec.ts
  e2e/iconMenu.spec.ts
  e2e/utils/draw.ts
  playwright.config.ts
Labels: testing

#296 fix diplan export example
  packages/clients/diplan/example/diplan-ui-one/index.html
  packages/clients/diplan/example/diplan-ui-one/setup.js
  packages/clients/diplan/example/diplan-ui-two/index.html
  packages/clients/diplan/example/polar-ui/index.html
  packages/clients/diplan/example/polar-ui/setup.js
  packages/clients/diplan/src/index.html
  packages/clients/diplan/src/setup.js
Labels: bug, documentation

#266 dish client: Feature/add separate layer for selected monument
  packages/clients/dish/CHANGELOG.md
  packages/clients/dish/src/addPlugins.ts
  packages/clients/dish/src/mapConfigurations/mapConfigIntern.ts
  packages/clients/dish/src/plugins/SelectionObject/SelectionObject.vue
  packages/clients/dish/src/plugins/SelectionObject/index.ts
  packages/clients/dish/src/plugins/SelectionObject/locales.ts
  packages/clients/dish/src/plugins/SelectionObject/store.ts
  packages/clients/dish/src/polar-client.ts
  packages/clients/dish/src/selectionLayer.ts
  packages/clients/dish/src/types.ts
  packages/plugins/Pins/CHANGELOG.md
  packages/plugins/Pins/src/index.ts
Labels: enhancement

#301 remove lint rules max-line
  .eslintrc.json
  e2e/draw.spec.ts
  packages/clients/bgw/src/addPlugins.ts
  packages/clients/diplan/e2e/draw.spec.ts
  packages/clients/diplan/example/diplan-ui-one/setup.js
  packages/clients/diplan/example/diplan-ui-two/setup.js
  packages/clients/diplan/example/polar-ui/setup.js
  packages/clients/diplan/example/services.js
  packages/clients/diplan/src/addPlugins.ts
  packages/clients/diplan/src/setup.js
  packages/clients/diplan/src/store/geoEditing/cutPolygons/index.ts
  packages/clients/diplan/src/store/geoEditing/mergePolygons.ts
  packages/clients/diplan/src/store/module.ts
  packages/clients/diplan/src/store/updateState/index.ts
  packages/clients/dish/src/addPlugins.ts
  packages/clients/dish/src/mapConfigurations/mapConfigIntern.ts
  packages/clients/dish/src/utils/extendGfi.ts
  packages/clients/generic/src/polar-client.ts
  packages/clients/meldemichel/src/addPlugins.ts
  packages/clients/meldemichel/src/mapConfigurations.ts
  packages/clients/meldemichel/src/store/module.ts
  packages/clients/snowbox/src/addPlugins.ts
  packages/clients/snowbox/src/exampleFeatureInformation.ts
  packages/clients/textLocator/src/addPlugins.ts
  packages/clients/textLocator/src/plugins/GeometrySearch/store/index.ts
  packages/core/src/components/MapContainer.vue
  packages/core/src/vuePlugins/actions/useExtendedMasterportalapiMarkers/index.ts
  packages/core/src/vuePlugins/vuex.ts
  packages/plugins/AddressSearch/src/store/actions.ts
  packages/plugins/Attributions/src/store/index.ts
  packages/plugins/Draw/src/store/actions.ts
  packages/plugins/Draw/src/store/createInteractions/createLassoInteractions.ts
  packages/plugins/Draw/src/store/index.ts
  packages/plugins/Filter/src/store/index.ts
  packages/plugins/GeoLocation/src/store/actions.ts
  packages/plugins/Gfi/src/store/actions/debouncedGfiRequest.ts
  packages/plugins/Gfi/src/store/actions/index.ts
  packages/plugins/Gfi/src/store/actions/setupMultiSelection.ts
  packages/plugins/Gfi/src/utils/requestGfiWfs.ts
  packages/plugins/IconMenu/src/store/index.ts
  packages/plugins/LayerChooser/src/store/index.ts
  packages/plugins/Pins/src/store/index.ts
  packages/plugins/ReverseGeocoder/src/store/index.ts
  packages/plugins/Scale/src/store/index.ts
  packages/plugins/Toast/src/store/index.ts
  packages/plugins/Zoom/src/store/index.ts
  packages/types/custom/core.ts
Labels: refactor

#300 Fix/disabled masks
  packages/clients/diplan/example/diplan-ui-one/config.js
  packages/clients/diplan/example/diplan-ui-two/config.js
  packages/clients/diplan/src/config.js
  packages/clients/diplan/src/plugins/IconMenu/IconMenuButton.vue
  packages/clients/diplan/src/plugins/LayerChooser/LayerChooser.vue
  packages/clients/diplan/src/plugins/LayerChooser/LayerWrapper.vue
  packages/plugins/IconMenu/src/components/IconMenu.vue
  packages/plugins/IconMenu/src/components/IconMenuButton.vue
  packages/plugins/LayerChooser/CHANGELOG.md
  packages/plugins/LayerChooser/src/components/LayerWrapper.vue
  packages/plugins/LayerChooser/src/components/Selection.vue
  packages/plugins/LayerChooser/src/index.ts
  packages/plugins/LayerChooser/src/store/index.ts
  packages/plugins/LayerChooser/src/types.ts
  packages/plugins/LayerChooser/src/utils/isLayerIdIncluded.ts
Labels: bug

#303 Fix/diplan layer options
  packages/clients/diplan/src/plugins/LayerChooser/LayerChooser.vue
  packages/plugins/LayerChooser/src/store/index.ts
  packages/plugins/LayerChooser/src/types.ts
Labels: enhancement

#304 fix measurement calculation
  packages/plugins/Draw/CHANGELOG.md
  packages/plugins/Draw/src/utils/createDrawStyle.ts
Labels: bug

#306 Fix/mobile gfi
  packages/plugins/Gfi/CHANGELOG.md
  packages/plugins/Gfi/src/components/Gfi.vue
Labels: bug

#307 Remove redundant if-statement breaking the open menu on resize
  packages/plugins/IconMenu/CHANGELOG.md
  packages/plugins/IconMenu/src/store/index.ts
  packages/plugins/IconMenu/tests/store.spec.ts
Labels: bug

#302 remove test service
  packages/clients/diplan/example/diplan-ui-one/config.js
  packages/clients/diplan/example/diplan-ui-two/config.js
  packages/clients/diplan/example/polar-ui/config.js
  packages/clients/diplan/src/config.js
Labels: refactor

#309 Feature/migrate geo editing
  e2e/draw.spec.ts
  package-lock.json
  packages/clients/diplan/CHANGELOG.md
  packages/clients/diplan/e2e/draw.spec.ts
  packages/clients/diplan/e2e/utils/openDiplan.ts
  packages/clients/diplan/package.json
  packages/clients/diplan/src/locales.ts
  packages/clients/diplan/src/store/module.ts
  packages/plugins/Draw/CHANGELOG.md
  packages/plugins/Draw/package.json
  packages/plugins/Draw/src/locales.ts
  packages/plugins/Draw/src/store/actions.ts
  packages/plugins/Draw/src/store/createInteractions/createCutInteractions/cutlery.ts
  packages/plugins/Draw/src/store/createInteractions/createCutInteractions/index.ts
  packages/plugins/Draw/src/store/createInteractions/createCutInteractions/makeDraw.ts
  packages/plugins/Draw/src/store/createInteractions/createCutInteractions/style.ts
  packages/plugins/Draw/src/store/createInteractions/createCutInteractions/types.ts
  packages/plugins/Draw/src/store/createInteractions/createDuplicateInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/createMergeInteractions.ts
  packages/plugins/Draw/src/store/createInteractions/index.ts
  packages/plugins/Draw/src/store/index.ts
  packages/plugins/Draw/src/types.ts
Labels: enhancement

#270 DISH Client: Fix/image protrudes from narrow gfi
  packages/clients/dish/CHANGELOG.md
  packages/clients/dish/src/plugins/Gfi/ContentExtern.vue
Labels: bug

#312 add default values to config in all spots
  packages/core/src/utils/createMap/index.ts
Labels: bug

#310 add draw revision
  package-lock.json
  packages/clients/snowbox/src/html/index.html
  packages/clients/snowbox/src/index.html
  packages/clients/snowbox/src/locales.ts
  packages/clients/snowbox/src/mapConfiguration.ts
  packages/clients/snowbox/src/polar-client.ts
  packages/plugins/Draw/CHANGELOG.md
  packages/plugins/Draw/README.md
  packages/plugins/Draw/package.json
  packages/plugins/Draw/src/locales.ts
  packages/plugins/Draw/src/store/actions.ts
  packages/plugins/Draw/src/store/index.ts
  packages/plugins/Draw/src/store/reviseFeatures/autofix.ts
  packages/plugins/Draw/src/store/reviseFeatures/cloneFeatureCollection.ts
  packages/plugins/Draw/src/store/reviseFeatures/enrichWithMetaServices.ts
  packages/plugins/Draw/src/store/reviseFeatures/index.ts
  packages/plugins/Draw/src/store/reviseFeatures/revisionStates.ts
  packages/plugins/Draw/src/store/reviseFeatures/validateGeoJson.ts
  packages/plugins/Draw/src/types.ts
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#298 add style preview client draft
  package-lock.json
  package.json
  packages/clients/stylePreview/API.md
  packages/clients/stylePreview/CHANGELOG.md
  packages/clients/stylePreview/LICENSE
  packages/clients/stylePreview/README.md
  packages/clients/stylePreview/example/index.html
  packages/clients/stylePreview/example/polar-example.js
  packages/clients/stylePreview/example/prod-example.html
  packages/clients/stylePreview/example/style.css
  packages/clients/stylePreview/package.json
  packages/clients/stylePreview/src/polar-client.ts
  packages/clients/stylePreview/src/stylePreview/features.ts
  packages/clients/stylePreview/src/stylePreview/index.ts
  packages/clients/stylePreview/src/stylePreview/updatePositions.ts
  packages/clients/stylePreview/src/stylePreview/updateStyles.ts
  packages/clients/stylePreview/vite.config.js
  packages/core/CHANGELOG.md
  packages/core/README.md
  pages/documentation.html
  scripts/buildPages.sh
Labels: enhancement

#305 Feature/pointer position
  @types/i18next.d.ts
  README.md
  e2e/draw.spec.ts
  package-lock.json
  packages/clients/snowbox/package.json
  packages/clients/snowbox/src/addPlugins.ts
  packages/clients/snowbox/src/mapConfiguration.ts
  packages/core/CHANGELOG.md
  packages/core/src/components/MapContainer.vue
  packages/core/src/utils/createMap/defaults.ts
  packages/plugins/PointerPosition/CHANGELOG.md
  packages/plugins/PointerPosition/LICENSE
  packages/plugins/PointerPosition/README.md
  packages/plugins/PointerPosition/package.json
  packages/plugins/PointerPosition/src/components/PointerPosition.vue
  packages/plugins/PointerPosition/src/components/index.ts
  packages/plugins/PointerPosition/src/index.ts
  packages/plugins/PointerPosition/src/locales.ts
  packages/plugins/PointerPosition/src/store/index.ts
  packages/plugins/PointerPosition/src/types.ts
  packages/plugins/PointerPosition/vite.config.js
  packages/types/custom/CHANGELOG.md
  packages/types/custom/core.ts
Labels: enhancement

#313 Addition of a login example to @polar/client-snowbox
  packages/clients/snowbox/src/authentication.ts
  packages/clients/snowbox/src/html/index.html
  packages/clients/snowbox/src/index.html
  packages/clients/snowbox/src/polar-client.ts
  packages/clients/snowbox/src/validateForm.ts
Labels: documentation, enhancement

#317 add region role to map div
  packages/core/CHANGELOG.md
  packages/core/src/components/MapContainer.vue
Labels: accessibility

#315 Fix/layer options tabbing
  packages/plugins/LayerChooser/CHANGELOG.md
  packages/plugins/LayerChooser/src/components/LayerWrapper.vue
  packages/plugins/LayerChooser/src/components/Options.vue
Labels: bug

#314 Remove need to call initializeLayerList for local service registers
  gettingStarted.md
  packages/clients/bgw/src/polar-client.ts
  packages/clients/dish/src/polar-client.ts
  packages/clients/textLocator/src/polar-client.ts
  packages/core/CHANGELOG.md
  packages/core/README.md
Labels: enhancement

#316 add missing aria-label
  packages/plugins/GeoLocation/CHANGELOG.md
  packages/plugins/GeoLocation/src/components/GeoLocation.vue
Labels: accessibility

#318 automated audit update
  package-lock.json
Labels: versioning

#319 update masterportalapi
  package-lock.json
  package.json
  packages/clients/bgw/package.json
  packages/clients/dish/package.json
  packages/clients/textLocator/package.json
  packages/core/package.json
  packages/lib/getCluster/package.json
  packages/lib/getFeatures/package.json
  packages/lib/invisibleStyle/package.json
  packages/lib/passesBoundaryCheck/package.json
  packages/plugins/AddressSearch/package.json
  packages/plugins/Attributions/package.json
  packages/plugins/Draw/package.json
  packages/plugins/Filter/package.json
  packages/plugins/GeoLocation/package.json
  packages/plugins/Gfi/package.json
  packages/plugins/LayerChooser/package.json
  packages/plugins/Legend/package.json
  packages/plugins/Pins/package.json
  packages/plugins/ReverseGeocoder/package.json
  packages/plugins/Scale/package.json
Labels: versioning

#321 Re-order some parts related to @polar/plugin-pointer-position
  packages/clients/snowbox/src/addPlugins.ts
  packages/plugins/PointerPosition/src/components/PointerPosition.vue
  packages/types/custom/core.ts
Labels: refactor

#325 Dish: apply new gfi highlight
  packages/clients/dish/src/mapConfigurations/mapConfigIntern.ts
Labels: refactor

#320 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation
